### ISSUE TITLE
Initialise vueApp

### ISSUE THREAD

**Issue by jolenegan** [BT3103AppDev1/final-project-l1-final-project-group-12#11]
Cc:

Hi

### Pain

Request for the initialization of a Vue.js application (VueApp) in this repository.

### Tasks

- [ ] Initialize a Vue.js application (VueApp) in this repository.

### Acceptance Criteria

- [ ] VueApp is successfully initialized.
- [ ] The project structure and settings are correctly configured.

### Screenshots

Thanks!
