### ISSUE TITLE
Smartfolio Stage 2: Enhancement Phase

### ISSUE THREAD

**Issue by mengyewgau** [BT3103AppDev1/final-project-l1-final-project-group-12#27]
Cc:

Hi

### Pain
As part of Smartfolio's development phase, as of Stage 1, we have completed integration of all basic landing pages and rolled out a minimal viable product. The objective of Stage 2 is to deploy the app, and implement CI/CD processes for continuous enhancement and improvement. 

### Tasks

- [x] UAT 
- [ ] Improve User Experience
- [ ] Address UI/UX bugs and speed issues
- [ ] Data collection and feature implementation

Thanks!
