### ISSUE TITLE
Watchlist Search Bar + Watchlist Table 

### ISSUE THREAD

**Issue by IleanaGoh** [BT3103AppDev1/final-project-l1-final-project-group-12#30]
Hi

### Describe the Bug

Users can only add to their watchlist using the correct ticker in full uppercase, they cannot add to their watchlist with the company name or in lower case. 

No popup-boxes to verify that stocks have been successfully added to their watchlist, or error popup to show invalid company name or ticker. 

For individual stock page (with price line graph), adding to the watchlist does not prompt any confirmation popup. 
Lack of button to access watchlist page from individual stock page. 
If user is not logged in, they can click the "add to watchlist" button and it even gives them confirmation that stock has been added, but subsequently a firebase error is thrown. 

For watchlist table, after users have added a stock, stock metrics are not being pulled and updated, unless user manually refreshes page. 

### To Reproduce
Try adding a stock on watchlist page 
Try adding stock from individual stock page 
Try adding stock from individual stock page despite not being logged in

### Expected Behaviour 

- Allow users to add with company name or ticker, and show confirmation popup or error popup 
- Stock metrics should be updated when user adds stock to watchlist 
- Users can only add to their watchlist if they are logged in

### Tasks

- [ ] On watchlist page, allow adding using company name. Show confirmation popup if successful, and error otherwise. 
- [ ] On individual stock page, show confirmation popup if successful 
- [ ] Edit code to refresh fetching of stock metrics after user has added a stock to watchlist. 
- [ ] Add button to allow users to navigate to watchlist from individual stock page
- [ ] If users are not logged in on individual stock page and tries to add stock to their watchlist, navigate them to the login page. 

### Acceptance Criteria

- [ ] Able to add to watchlist using company name (from watchlist page) 
- [ ] Prompts to indicate success or failure
- [ ] Stock metrics to be updated after adding of stock + confirmation prompt 
- [ ] Back buttons navigate to the previous page user was on
- [ ] Users who are not logged in but try to add to their watchlist from the individual stock page will be directed to the login page 

Thanks!
